databases:
  - name: rails_blog
    databaseName: rails_blog
    user: rails_blog

services:
  - type: web
    name: rails_blog
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false